### ISSUE TITLE
support for intermediate run start points

### ISSUE THREAD

**Issue by neelgala** [riscv/riscof#1]
Currently the `riscof run` command starts always by creating a database of the suite, generating a test-list from it, and then running the tests. However the database generation and test-list generation are quite time consuming functions. While debugging bugs one would like to skip these everytime and simply start from the test-list itself. 

Proposal:
To the `run` command add 2 more sub args: `--dbfile` and `--testlist`. These arguments along with the `--suite` will all be mutually exclusive. Following is what is done for each args:

- `--suite`: run database generation, generate test-list and run tests on target and reference
- `--dbfile`: generate test-list and run tests on target and reference (assumes the dbfile is correct and updated)
- `--testfile`: directly run tests on the target and reference (assumes the testlist has been correctly generated)

Only one of the above should be enabled at any point.

One other subargs could be to run the tests only on the reference or the target and then quit (before performing the signature comparisons) This can be achieved by having `--no-ref-run` and `--no-dut-run` sub args to the `run` command

**Comment by bilalsakhawat-10xe** [comment]
Hi @neelgala! Can you assign this issue to me?

**Comment by neelgala** [comment]
@bilalsakhawat-10xe assigned to you. I would also suggest branching off from migration-fix branch.. that is a soon to be merged branch to master with some pretty large changes.

**Comment by bilalsakhawat-10xe** [comment]
Thanks @neelgala. Sure I'll branch off from migration-fix branch.

**Comment by neelgala** [comment]
fixed in #12
